gem:
  build: .
  command: rake
  links:
    - redis:redis.local
    - mysql:mysql.local
    - mongodb:mongodb.local
    - postgres:postgres.local
  volumes:
    - ./lib:/gem/lib/
    - ./spec:/gem/spec/
    - ./features:/gem/features/
    - ./Rakefile:/gem/Rakefile

redis:
  image: redis:3.0.3

mysql:
  image: mysql:5.6.26
  command: "/entrypoint.sh mysqld"
  environment:
    - MYSQL_ROOT_PASSWORD=secret

mongodb:
  image: mongo:2.6.10

postgres:
  image: postgres:9.3.9
  command: "/docker-entrypoint.sh postgres"
