mysql:
  adapter: mysql
  database: database_cleaner_test
  username: root
  password:
  host: 127.0.0.1
  port: 3306
  encoding: utf8

mysql2:
  adapter: mysql2
  database: database_cleaner_test
  username: root
  password:
  host: 127.0.0.1
  port: 3306
  encoding: utf8

postgres:
  adapter: postgresql
  database: database_cleaner_test
  username: postgres
  password:
  host: 127.0.0.1
  encoding: unicode
  template: template0

sqlite3:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
